model: 
 in_channels: 3
 out_channels: 1

dataset: # All dataset paths must be relative to the project root folder
  train_img_dir: "datasets/carvana/train_images/" 
  train_mask_dir: "datasets/carvana/train_masks/"
  val_img_dir: "datasets/carvana/val_images/"
  val_mask_dir: "datasets/carvana/val_masks/"
  test_img_dir: "datasets/carvana/test_images/"
  test_mask_dir: "datasets/carvana/test_masks/"

logs:
  tensorboard: 
    log_dir: "logs/tensorboard/"
  checkpoints:
    checkpoint_dir: "logs/checkpoints/"
    checkpoint_prefix: checkpoint.pth.tar
  saved_images:
    saved_images_dir: "logs/saved_images/"
  
train:
  device: "cuda"
  batch_size: 20
  num_epochs: 50
  learning_rate: 1e-4

train_transform:
  resize:
    image_height: 320
    image_width: 480
  rotate: 
    limit: 35 #rotations would be done in the range [-35, 35] degrees
    p: 1.0
  horizontal_flip: 
    p: 0.1
  vertical_flip:
    p: 1.0
  normalize:
    channel_mean: 0.0
    channel_std: 1.0
    max_pixel_value: 255.0 

dataloader:
  pin_memory: True 
  num_workers: 1  # having one queue for batch dataloading seems optimal ==> https://www.youtube.com/watch?v=kWVgvsejXsE
  
eval_mode: False